services:
  nodejs:
    from: 'node:4.2.1'

staging:
  prepare:
    - npm install
  service: nodejs
  folder: /app
  port: 80
  cmd: node index.js
  env:
    - NODE_ENV=production
    - PORT=80

staging2:
  prepare:
    - npm install
  service: nodejs
  folder: /app
  port: 80
  cmd: npm start
  env:
    - NODE_ENV=production
    - PORT=80


tests:
  prepare:
    - npm install
  service: nodejs
  folder: /app
  cmd: 'echo "........"'
  env:
    - NODE_ENV=production
